### PR TITLE
Ensure directory exists before writing unzipped file

### LINKED ISSUE #21: Installing FF fails with v9
```
C:\> set PUPPETEER_PRODUCT=firefox

C:\> deno run -A --unstable https://deno.land/x/puppeteer@9.0.0/install.ts
Download https://deno.land/x/puppeteer@9.0.0/install.ts
Check https://deno.land/x/puppeteer@9.0.0/install.ts

100.00% 21.1s 83721209/83721209

error: Uncaught (in promise) NotFound: The system cannot find the path specified. (os error 3)
      await Deno.writeFile(ff, content);
      ^
    at unwrapOpResult (deno:core/core.js:99:13)
    at async open (deno:runtime/js/40_files.js:46:17)
    at async Object.writeFile (deno:runtime/js/40_write_file.js:58:18)
    at async JSZip.unzip (https://deno.land/x/puppeteer@9.0.0/vendor/puppeteer-core/vendor/zip/mod.ts:203:7)
    at async extractZip (https://deno.land/x/puppeteer@9.0.0/src/deno/BrowserFetcher.ts:473:3)
    at async BrowserFetcher.download (https://deno.land/x/puppeteer@9.0.0/src/deno/BrowserFetcher.ts:283:7)
    at async https://deno.land/x/puppeteer@9.0.0/install.ts:34:27

C:\> deno -V
deno 1.9.2
```

Installing Chrome worked just fine.

### PR DESCRIPTION
**Pull request by MarkTiedemann**
Closes #21.

### CODE REVIEW

File: vendor/puppeteer-core/vendor/zip/mod.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import _JSZip from "https://dev.jspm.io/jszip@3.5.0";
-import { walk, WalkOptions } from "https://deno.land/std@0.93.0/fs/walk.ts";
-import { join, SEP } from "https://deno.land/std@0.93.0/path/mod.ts";
+import { ensureDir, walk, WalkOptions } from "https://deno.land/std@0.93.0/fs/mod.ts";
```
Comment (lucacasonato) [inline vendor/puppeteer-core/vendor/zip/mod.ts:2]: can you import from the individual modules instead of from `mod.ts`? want to keep deps as slim as possible.

**Review by lucacasonato — COMMENTED** [review]
LGTM, just a minor comment

File: vendor/puppeteer-core/vendor/zip/mod.ts (hunk 1 above)
Comment (MarkTiedemann) [reply vendor/puppeteer-core/vendor/zip/mod.ts]: Sure.

**Review by lucacasonato — APPROVED** [review]
LGTM, thanks
